SOL-14426 Updated the Version for Crypto.
solidatus/monstache pull request #5
Opened 2024-05-06 08:38 UTC by Eknath-Sable

Updated the Version for Crypto to v0.17

2024-05-06 08:46 UTC, ratneshdubeysolidatus approved these changes
LGTM

2024-05-07 06:32 UTC, mix4242 requested changes
Please remember to bump monstache version
Also we seem to be keeping a CHANGELOG in the `Solidatus-README.md` file

2024-05-07 07:59 UTC, Eknath-Sable commented
> Please remember to bump monstache version Also we seem to be keeping a CHANGELOG in the `Solidatus-README.md` file

Added comment and bumped monstache version to 6.7.10+5

2024-05-07 08:01 UTC, mix4242 requested changes

2024-05-07 08:01 UTC, mix4242 commented on Solidatus-README.md
> +Golang has 1 vulnerability CVE-2023-48795 which was fixed in golang.org/x/crypto v0.17.0 hence manually updated go.mod to use 1.21.6. (latest on main branch was 1.21.3)
The second half of this sentence doesn't sound accurate 👀 

May be worth also explaining why `golang.org/x/sys` & `golang.org/x/text` were bumped (I'm assuming as they had to be when `crypto` was bumped?)

2024-05-07 08:33 UTC, mix4242 approved these changes

2024-05-07 08:35 UTC, ratneshdubeysolidatus approved these changes

2024-05-07 08:35 UTC, merged